name: Create Release Package

on:
  create:

jobs:
  is_release:
    if: contains(github.ref, 'beta') == false
    runs-on: ubuntu-latest

    steps:
    - name: Check
      run: |
        echo ${{ github.event }}
        echo ${{ github.event_name }}
        echo ${{ github.event_path }}
        echo ${{ github.ref }}

  package:
    needs: is_release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Release Package
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WAGO_API_KEY: ${{ secrets.WAGO_API_KEY }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get install pandoc
        curl -s https://raw.githubusercontent.com/RealUI/packager/RealUI/release.sh -o release.sh
        bash release.sh -L -p 88269 -w 16068
